# Generated by Django 5.1.7 on 2025-03-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issue_attachment_issue_priority_alter_issue_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='attachment',
        ),
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(default='Medium', max_length=20),
        ),
    ]
