# Generated by Django 5.1.7 on 2025-04-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_remove_issue_attachment_alter_issue_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('new', 'Nouveau'), ('open', 'Ouvert'), ('in-progress', 'En cours'), ('resolved', 'Résolu'), ('closed', 'Fermé')], max_length=50),
        ),
    ]
